### ISSUE TITLE
compatibility error? python 3.7

### ISSUE THREAD

**Issue by rowlinglulu** [howl-anderson/Chinese_models_for_SpaCy#17]
I ran the following code: 

from spacy import displacy

import zh_core_web_sm

nlp = zh_core_web_sm.load()

error                                     Traceback (most recent call last)
<ipython-input-12-b1a486d0b170> in <module>
      3 import zh_core_web_sm
      4 
----> 5 nlp = zh_core_web_sm.load()
      6 def main():
      7     doc = nlp("王小明在北京的清华大学读书")

/anaconda3/envs/rowEnv/lib/python3.6/site-packages/zh_core_web_sm/__init__.py in load(**overrides)
     10 
     11 def load(**overrides):
---> 12     return load_model_from_init_py(__file__, **overrides)

/anaconda3/envs/rowEnv/lib/python3.6/site-packages/spacy/util.py in load_model_from_init_py(init_file, **overrides)
    188     if not model_path.exists():
    189         raise IOError(Errors.E052.format(path=path2str(data_path)))
--> 190     return load_model_from_path(data_path, meta, **overrides)
    191 
    192 

/anaconda3/envs/rowEnv/lib/python3.6/site-packages/spacy/util.py in load_model_from_path(model_path, meta, **overrides)
    171             component = nlp.create_pipe(name, config=config)
    172             nlp.add_pipe(component, name=name)
--> 173     return nlp.from_disk(model_path)
    174 
    175 

/anaconda3/envs/rowEnv/lib/python3.6/site-packages/spacy/language.py in from_disk(self, path, exclude, disable)
    784             # Convert to list here in case exclude is (default) tuple
    785             exclude = list(exclude) + ["vocab"]
--> 786         util.from_disk(path, deserializers, exclude)
    787         self._path = path
    788         return self

/anaconda3/envs/rowEnv/lib/python3.6/site-packages/spacy/util.py in from_disk(path, readers, exclude)
    609         # Split to support file names like meta.json
    610         if key.split(".")[0] not in exclude:
--> 611             reader(path / key)
    612     return path
    613 

/anaconda3/envs/rowEnv/lib/python3.6/site-packages/spacy/language.py in <lambda>(p)
    774         deserializers["meta.json"] = lambda p: self.meta.update(srsly.read_json(p))
    775         deserializers["vocab"] = lambda p: self.vocab.from_disk(p) and _fix_pretrained_vectors_name(self)
--> 776         deserializers["tokenizer"] = lambda p: self.tokenizer.from_disk(p, exclude=["vocab"])
    777         for name, proc in self.pipeline:
    778             if name in exclude:

tokenizer.pyx in spacy.tokenizer.Tokenizer.from_disk()

tokenizer.pyx in spacy.tokenizer.Tokenizer.from_bytes()

/anaconda3/envs/rowEnv/lib/python3.6/re.py in compile(pattern, flags)
    231 def compile(pattern, flags=0):
    232     "Compile a regular expression pattern, returning a pattern object."
--> 233     return _compile(pattern, flags)
    234 
    235 def purge():

/anaconda3/envs/rowEnv/lib/python3.6/re.py in _compile(pattern, flags)
    299     if not sre_compile.isstring(pattern):
    300         raise TypeError("first argument must be string or compiled pattern")
--> 301     p = sre_compile.compile(pattern, flags)
    302     if not (flags & DEBUG):
    303         if len(_cache) >= _MAXCACHE:

/anaconda3/envs/rowEnv/lib/python3.6/sre_compile.py in compile(p, flags)
    560     if isstring(p):
    561         pattern = p
--> 562         p = sre_parse.parse(p, flags)
    563     else:
    564         pattern = None

/anaconda3/envs/rowEnv/lib/python3.6/sre_parse.py in parse(str, flags, pattern)
    853 
    854     try:
--> 855         p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
    856     except Verbose:
    857         # the VERBOSE flag was switched on inside the pattern.  to be

/anaconda3/envs/rowEnv/lib/python3.6/sre_parse.py in _parse_sub(source, state, verbose, nested)
    414     while True:
    415         itemsappend(_parse(source, state, verbose, nested + 1,
--> 416                            not nested and not items))
    417         if not sourcematch("|"):
    418             break

/anaconda3/envs/rowEnv/lib/python3.6/sre_parse.py in _parse(source, state, verbose, nested, first)
    525                     break
    526                 elif this[0] == "\\":
--> 527                     code1 = _class_escape(source, this)
    528                 else:
    529                     code1 = LITERAL, _ord(this)

/anaconda3/envs/rowEnv/lib/python3.6/sre_parse.py in _class_escape(source, escape)
    334         if len(escape) == 2:
    335             if c in ASCIILETTERS:
--> 336                 raise source.error('bad escape %s' % escape, len(escape))
    337             return LITERAL, ord(escape[1])
    338     except ValueError:

error: bad escape \p at position 275

**Comment by howl-anderson** [comment]
Can provide more detailed information about your environment: OS, python version, spacy version etc?

**Comment by howl-anderson** [comment]
> compatibility error? python 3.7

But I see python version is 3.6 in log message `/anaconda3/envs/rowEnv/lib/python3.6/site-packages/spacy/language.py in (p)`, so make sure your information is correct and detailed.

**Comment by rowlinglulu** [comment]
Thank you for the prompt response!
OS: 10.14.2
my python version is 3.7.0, I think I have multiple python versions that's why it might be confusing
spacy version is 2.1.3

**Comment by howl-anderson** [comment]
As the error log said, you maybe actual using python 3.6 rather than 3.7. 
You can try downgrade spacy to 2.0.x which is the version I develop package on. I am not sure this package works on spacy 2.1.x for now.

**Comment by itcmixu** [comment]
same error on Ubuntu 18.0.4 Bionic, Python 3.7.1, spaCy 2.1.3.

but after i downgraded spaCy from 2.1.3 to 2.0.1 successfully, i got another error as below:
[error.txt](https://github.com/howl-anderson/Chinese_models_for_SpaCy/files/3054709/error.txt)

what should i do?

**Comment by echan00** [comment]
Same here, I am also getting the original error with Python3.7 and Spacy2.1.3

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/spacy/util.py", line 133, in load_model
    return load_model_from_path(Path(name), **overrides)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/spacy/util.py", line 173, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/spacy/language.py", line 786, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/spacy/util.py", line 611, in from_disk
    reader(path / key)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/spacy/language.py", line 776, in <lambda>
    deserializers["tokenizer"] = lambda p: self.tokenizer.from_disk(p, exclude=["vocab"])
  File "tokenizer.pyx", line 390, in spacy.tokenizer.Tokenizer.from_disk
  File "tokenizer.pyx", line 436, in spacy.tokenizer.Tokenizer.from_bytes
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/re.py", line 234, in compile
    return _compile(pattern, flags)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/sre_parse.py", line 536, in _parse
    code1 = _class_escape(source, this)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/sre_parse.py", line 337, in _class_escape
    raise source.error('bad escape %s' % escape, len(escape))
re.error: bad escape \p at position 275
```

**Comment by howl-anderson** [comment]
@itcmixu Try to reinstall thinc. This is a weird issue sometime happen sometime not.

**Comment by howl-anderson** [comment]
@echan00 Try downgrade SpaCy to 2.0.x

**Comment by rowlinglulu** [comment]
> As the error log said, you maybe actual using python 3.6 rather than 3.7.
> You can try downgrade spacy to 2.0.x which is the version I develop package on. I am not sure this package works on spacy 2.1.x for now.

Thank you! Problem solved.
Downgraded to Spacy 2.0.11 (operated in Python 3.6)

**Comment by itcmixu** [comment]
> @itcmixu Try to reinstall thinc. This is a weird issue sometime happen sometime not.

according to your instruction, i uninstall and reinstall Thinc from 6.10.3 to 7.0.4.  i got incompatible 
 error of cymem with 2.0.2, checked the installation log, and downgrade cymem to 1.31.2.

but i finally stuck into error "ValueError: shapes (9,512) and (640,384) not aligned: 512 (dim 1) != 640 (dim 0)", please see detail log in attachment.
[erro.txt](https://github.com/howl-anderson/Chinese_models_for_SpaCy/files/3056644/erro.txt)


do we have Docker envs? always have compatibility issues.

**Comment by howl-anderson** [comment]
@rowlinglulu I glad your problem is solved, could you do me a favor, using `pip freeze` list all installed python packages and version info to help @itcmixu solve dependency issue? Thank you so much!

@itcmixu It's uncommon that a SDK package provide docker image for user. I will try to find the root cause of compatibility issue and update README.

**Comment by rowlinglulu** [comment]
> @rowlinglulu I glad your problem is solved, could you do me a favor, using `pip freeze` list all installed python packages and version info to help @itcmixu solve dependency issue? Thank you so much!
> 
> @itcmixu It's uncommon that a SDK package provide docker image for user. I will try to find the root cause of compatibility issue and update README.

Happy to! @itcmixu Please see attached for more information

absl-py==0.7.0
appnope==0.1.0
asn1crypto==0.24.0
astor==0.7.1
attrs==19.1.0
backcall==0.1.0
bleach==3.1.0
blis==0.2.4
certifi==2019.3.9
cffi==1.12.2
chardet==3.0.4
cryptography==2.6.1
cycler==0.10.0
cymem==1.31.2
cytoolz==0.9.0.1
decorator==4.4.0
defusedxml==0.5.0
dill==0.2.9
en-core-web-lg==2.1.0
entrypoints==0.3
gast==0.2.2
graphviz==0.8.4
grpcio==1.16.1
h5py==2.9.0
idna==2.8
imbalanced-learn==0.4.3
ipykernel==5.1.0
ipython==7.4.0
ipython-genutils==0.2.0
jedi==0.13.3
jieba==0.39
Jinja2==2.10
jsonschema==2.6.0
jupyter-client==5.2.4
jupyter-core==4.4.0
Keras==2.2.4
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
kiwisolver==1.0.1
Markdown==3.0.1
MarkupSafe==1.1.1
matplotlib==3.0.3
mistune==0.8.4
mkl-fft==1.0.10
mkl-random==1.0.2
mock==2.0.0
msgpack==0.6.1
msgpack-numpy==0.4.4.2
msgpack-python==0.5.6
murmurhash==0.28.0
nb-conda==2.2.1
nb-conda-kernels==2.2.0
nbconvert==5.4.1
nbformat==4.4.0
notebook==5.7.8
numpy==1.16.2
olefile==0.46
pandas==0.24.2
pandocfilters==1.4.2
parso==0.3.4
pathlib==1.0.1
patsy==0.5.1
pbr==5.1.3
pexpect==4.6.0
pickleshare==0.7.5
Pillow==5.4.1
plac==0.9.6
plotly==3.7.0
preshed==1.0.1
prometheus-client==0.6.0
prompt-toolkit==2.0.9
protobuf==3.6.1
ptyprocess==0.6.0
pycparser==2.19
pydot==1.3.0
Pygments==2.3.1
pygraphviz==1.3
pyOpenSSL==19.0.0
pyparsing==2.3.1
pyrsistent==0.14.11
PySocks==1.6.8
python-dateutil==2.8.0
pytz==2018.9
PyYAML==5.1
pyzmq==18.0.0
regex==2017.4.5
requests==2.21.0
retrying==1.3.3
scikit-learn==0.20.3
scipy==1.2.1
seaborn==0.9.0
Send2Trash==1.5.0
six==1.12.0
spacy==2.0.11
srsly==0.0.5
statsmodels==0.9.0
tabulate==0.8.3
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
termcolor==1.1.0
terminado==0.8.1
testpath==0.4.2
thinc==6.10.3
toolz==0.9.0
tornado==6.0.2
tqdm==4.31.1
traitlets==4.3.2
ujson==1.35
urllib3==1.24.1
wasabi==0.2.1
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
wrapt==1.10.11
zh-core-web-sm==2.0.3
zh-model==2.1.0

**Comment by echan00** [comment]
@howl-anderson  thanks, I can confirm downgrade to spacy 2.0.11 works now

**Comment by echan00** [comment]
Unfortunately, after downgrading to spacy 2.0.11 I can no longer load the large english model
`nlp = spacy.load('en_core_web_lg')`

Error below:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/spacy/__init__.py", line 15, in load
    return util.load_model(name, **overrides)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/spacy/util.py", line 114, in load_model
    return load_model_from_package(name, **overrides)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/spacy/util.py", line 135, in load_model_from_package
    return cls.load(**overrides)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/en_core_web_lg/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/spacy/util.py", line 173, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/spacy/util.py", line 156, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/spacy/language.py", line 653, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/spacy/language.py", line 649, in <lambda>
    deserializers[name] = lambda p, proc=proc: proc.from_disk(p, vocab=False)
  File "pipeline.pyx", line 643, in spacy.pipeline.Tagger.from_disk
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "pipeline.pyx", line 626, in spacy.pipeline.Tagger.from_disk.load_model
  File "pipeline.pyx", line 627, in spacy.pipeline.Tagger.from_disk.load_model
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thinc/neural/_classes/model.py", line 352, in from_bytes
    copy_array(dest, param[b'value'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thinc/neural/util.py", line 48, in copy_array
    dst[:] = src
ValueError: could not broadcast input array from shape (96) into shape (128)
```

**Comment by howl-anderson** [comment]
@echan00 It seems this issue is not related with or caused by Chinese SpaCy model. I suggest you clean whole python environment and reinstall it with specific version. SpaCy models are sensitive to SpaCy version.

**Comment by echan00** [comment]
Yes, it is not related to Chinese SpaCy model. Based on the forums of SpaCy, it seems like 2.0.11 had issues with the large English model which then got resolved in later releases.

Any chance we will see Chinese SpaCy model compatible with future SpaCy versions? I can also try to help on this

**Comment by itcmixu** [comment]
> > @rowlinglulu I glad your problem is solved, could you do me a favor, using `pip freeze` list all installed python packages and version info to help @itcmixu solve dependency issue? Thank you so much!
> > @itcmixu It's uncommon that a SDK package provide docker image for user. I will try to find the root cause of compatibility issue and update README.
> 
> Happy to! @itcmixu Please see attached for more information
> 
> absl-py==0.7.0
> appnope==0.1.0
> asn1crypto==0.24.0
> astor==0.7.1
> attrs==19.1.0
> backcall==0.1.0
> bleach==3.1.0
> blis==0.2.4
> certifi==2019.3.9
> cffi==1.12.2
> chardet==3.0.4
> cryptography==2.6.1
> cycler==0.10.0
> cymem==1.31.2
> cytoolz==0.9.0.1
> decorator==4.4.0
> defusedxml==0.5.0
> dill==0.2.9
> en-core-web-lg==2.1.0
> entrypoints==0.3
> gast==0.2.2
> graphviz==0.8.4
> grpcio==1.16.1
> h5py==2.9.0
> idna==2.8
> imbalanced-learn==0.4.3
> ipykernel==5.1.0
> ipython==7.4.0
> ipython-genutils==0.2.0
> jedi==0.13.3
> jieba==0.39
> Jinja2==2.10
> jsonschema==2.6.0
> jupyter-client==5.2.4
> jupyter-core==4.4.0
> Keras==2.2.4
> Keras-Applications==1.0.7
> Keras-Preprocessing==1.0.9
> kiwisolver==1.0.1
> Markdown==3.0.1
> MarkupSafe==1.1.1
> matplotlib==3.0.3
> mistune==0.8.4
> mkl-fft==1.0.10
> mkl-random==1.0.2
> mock==2.0.0
> msgpack==0.6.1
> msgpack-numpy==0.4.4.2
> msgpack-python==0.5.6
> murmurhash==0.28.0
> nb-conda==2.2.1
> nb-conda-kernels==2.2.0
> nbconvert==5.4.1
> nbformat==4.4.0
> notebook==5.7.8
> numpy==1.16.2
> olefile==0.46
> pandas==0.24.2
> pandocfilters==1.4.2
> parso==0.3.4
> pathlib==1.0.1
> patsy==0.5.1
> pbr==5.1.3
> pexpect==4.6.0
> pickleshare==0.7.5
> Pillow==5.4.1
> plac==0.9.6
> plotly==3.7.0
> preshed==1.0.1
> prometheus-client==0.6.0
> prompt-toolkit==2.0.9
> protobuf==3.6.1
> ptyprocess==0.6.0
> pycparser==2.19
> pydot==1.3.0
> Pygments==2.3.1
> pygraphviz==1.3
> pyOpenSSL==19.0.0
> pyparsing==2.3.1
> pyrsistent==0.14.11
> PySocks==1.6.8
> python-dateutil==2.8.0
> pytz==2018.9
> PyYAML==5.1
> pyzmq==18.0.0
> regex==2017.4.5
> requests==2.21.0
> retrying==1.3.3
> scikit-learn==0.20.3
> scipy==1.2.1
> seaborn==0.9.0
> Send2Trash==1.5.0
> six==1.12.0
> spacy==2.0.11
> srsly==0.0.5
> statsmodels==0.9.0
> tabulate==0.8.3
> tensorboard==1.13.1
> tensorflow==1.13.1
> tensorflow-estimator==1.13.0
> termcolor==1.1.0
> terminado==0.8.1
> testpath==0.4.2
> thinc==6.10.3
> toolz==0.9.0
> tornado==6.0.2
> tqdm==4.31.1
> traitlets==4.3.2
> ujson==1.35
> urllib3==1.24.1
> wasabi==0.2.1
> wcwidth==0.1.7
> webencodings==0.5.1
> Werkzeug==0.14.1
> wrapt==1.10.11
> zh-core-web-sm==2.0.3
> zh-model==2.1.0

i made installed package list comparison with rollinglulu's list, and reconfig my packages same as his/hers. but same error "ValueError: shapes (9,512) and (640,384) not aligned: 512 (dim 1) != 640 (dim 0)"! my god! took a whole day already! attachment is package list side by side comparison result.
[packagediff.txt](https://github.com/howl-anderson/Chinese_models_for_SpaCy/files/3059369/packagediff.txt)

**Comment by howl-anderson** [comment]
> Yes, it is not related to Chinese SpaCy model. Based on the forums of SpaCy, it seems like 2.0.11 had issues with the large English model which then got resolved in later releases.

You can try later version of 2.0.xx (latest 2.0.xx version is v2.0.18), it maybe fix this issue.

> Any chance we will see Chinese SpaCy model compatible with future SpaCy versions? I can also try to help on this

For now, I have no plan to build model for SpaCy 2.1.x , the reason is simple: 2.1.x just released 23 days ago, it's still not stable enough. When 2.1.x is stable, Chinese model will be ready for users.

**Comment by howl-anderson** [comment]
@itcmixu I don't understand the purpose you sent my the pacakgediff.txt since you already ` reconfig my packages same as his/hers`. Can you try reinstall packages in a clean python environment. if not work, please provide package list and detailed info in the error log.

**Comment by echan00** [comment]
> You can try later version of 2.0.xx (latest 2.0.xx version is v2.0.18), it maybe fix this issue.

Yes, I tried v2.0.18 but it still doesn't support loading the large english model. I guess I will need to wait

**Comment by howl-anderson** [comment]
@echan00 A workaround way is using different SpaCy for different model. :)

**Comment by echan00** [comment]
> @echan00 A workaround way is using different SpaCy for different model. :)

I looked around online but didn't find ways to load two different versions of a python module, one way I can think of is replicate the entire module and change the name? Would you know any other ways?

**Comment by howl-anderson** [comment]
@echan00 Two different versions of a python module cannot simultaneously exist in same python process. But most user don't use Chinese and English model at same time, so you can using different model in different python environment and script separately.

**Comment by itcmixu** [comment]
hey guys,

finally i worked it out by installing a new virtualenv for spacy, the most important package version is as below:
--------------------------------
spacy 2.0.11
zh-core-web-sm 2.0.3
thinc 6.10.3
jieba 0.39
---------------------------

the chinese model is loaded and NER is working. but still many issues left over.

here is my screen output:
-----------------------------------------------------
(spacy) (base) mike@DiveIntoDeepLearning:~$ pwd
/home/mike
(spacy) (base) mike@DiveIntoDeepLearning:~$ python
Python 3.7.1 (default, Dec 14 2018, 19:28:38) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> nlp = spacy.load("zh_core_web_sm")
>>> doc = nlp("习近平关心的这个少数民族 70年间实现两次跨越")
Building prefix dict from the default dictionary ...
Dumping model to file cache /tmp/jieba.cache
Loading model cost 2.122 seconds.
Prefix dict has been built succesfully.

>>> for ent in doc.ents:
...     print(ent.text, ent.label_)
...
习近平 ORG

>>> print("Verbs:", [token.lemma_ for token in doc if token.pos_ == "VERB"])
Verbs: []


>>> for chunk in doc.noun_chunks:
...     print(chunk.text)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "doc.pyx", line 503, in __get__
TypeError: 'NoneType' object is not callable
>>> 
-----------------------------------------------------------------

as you can see, 
a) still not support VERB
b) NER tagging is not correct
c) not support noun_chunks

PS. 
a) not support en_core_web_lg

**Comment by howl-anderson** [comment]
@itcmixu 
1. POS is a known issue (see [TODO in README.md](https://github.com/howl-anderson/Chinese_models_for_SpaCy#todo-list))
2. NER **can be incorrect**, no such model can work correctly in any case. This model is using outdate corpus, which don't have information about new thing. For cases this model can correctly work, please see blow PS.
3. I didn't test code with using `noun_chunks`, I will check it when I update model.

PS: You can reference [my code](https://github.com/howl-anderson/Chinese_models_for_SpaCy/blob/master/notebooks/demo.ipynb) to test this model which I already tested it using same script for a long time.

**Comment by itcmixu** [comment]
> @itcmixu
> 
> 1. POS is a known issue (see [TODO in README.md](https://github.com/howl-anderson/Chinese_models_for_SpaCy#todo-list))
> 2. NER **can be incorrect**, no such model can work correctly in any case. This model is using outdate corpus, which don't have information about new thing. For cases this model can correctly work, please see blow PS.
> 3. I didn't test code with using `noun_chunks`, I will check it when I update model.
> 
> PS: You can reference [my code](https://github.com/howl-anderson/Chinese_models_for_SpaCy/blob/master/notebooks/demo.ipynb) to test this model which I already tested it using same script for a long time.

thank you. i am keeping to investigate spaCy more and more deeper. just now, i found i cound just load 'zh_core_web_sm' instead of 'jieba'. so what's the relationship of those two packages? is 'zh_core_web_sm' a wrapper of 'jieba' or they are totally independent ones?

**Comment by howl-anderson** [comment]
@itcmixu Sorry, I don't remember such details since I already work on other project for months, and I don't have time for this for now. I suggest you read the officially docs, it contains how the model works and so on. Officially things better than me in almost every way.

**Comment by howl-anderson** [comment]
@itcmixu @echan00 @rowlinglulu Chinese model for SpaCy 2.2.x already released, it should fix this issue.
